---

  - name: copy munge.key file to the slurm worker node
    copy:
      src: "{{ local_munge_key }}"
      dest: "/etc/munge/munge.key"
      owner: munge
      group: munge
      mode: '0400'

  - name: Restart Munge service
    service: name=munge state=restarted
    when: not munge_key.stat.exists

  - name: Make sure the munge service is started
    service: name=munge state=started
